version: "3.4"
services:
  server:
    image: node:14
    volumes:
    - ./server:/server
    working_dir: /server
    command: npm start
    env_file:
      - .env
    networks:
      - exterior
      - db

  db:
    image: postgres:9.6-alpine
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - db

networks:
  exterior:
    internal: false
  db:
    internal: true

volumes:
    db_data: { }