version: "3.4"
services:

  client:
    image: node:14
    volumes:
    - ./client:/client
    working_dir: /client
    command: npm start
    ports:
    - '80:3000'
    networks:
      - exterior

  server:
    depends_on:
      - db
    image: node:14
    volumes:
    - ./server:/server
    working_dir: /server
    command: npm run watch
    ports:
    - '81:81'
    env_file:
      - .env
    networks:
      - exterior
      - db

  db:
    image: postgres:9.6-alpine
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    networks:
      - db

networks:
  exterior:
    internal: false
  db:
    internal: true

volumes:
    db_data: { }